version: '3.4'

services:
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_PASSWORD: postgrespass
        ports:
            - 5432:5432
        volumes:
            - ./postgres-initialization:/docker-entrypoint-initdb.d